### ISSUE TITLE
Port for neoforge

### ISSUE THREAD

**Issue by Z0mChips** [ascpixi/disconnect-packet-fix#1]
Hey man I am having the same issue as your mod fixes on fabric, do you think you would be able to port it for neoforge ? I am annoyed that I cannot see shit in my console… 
Anyways, Thanks a lot !

**Comment by Z0mChips** [comment]
Okay thanks !

Hoping that it’s not too complicated haha

**Comment by ascpixi** [comment]
Sorry that this took such a long time, but this is practically finished. I'm running the mod on my own personal server now to catch any potential bugs. Expect a NeoForge release soon™️!
